FROM: boot-builder/spring-boot-builder-v2:latest

#these packages are installed just for pasbe, so that the mhf binary can work
RUN INSTALL_PKGS=" glibc-devel.i686 ncurses-libs.i686 libxml2-devel.i686 " && \
    yum install -y --enablerepo=centosplus $INSTALL_PKGS && \
    rpm -V $INSTALL_PKGS && \
    yum clean all -y 

USER 1001

# Set the default CMD to print the usage of the language image
CMD $STI_SCRIPTS_PATH/usage
